version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "8080:8080"
    networks:
      - redapp

  frontend:
    build:
      context: ../sumativa2/frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - redapp

networks:
  redapp:
    driver: bridge
